AWSTemplateFormatVersion: "2010-09-09"
Resources:
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Datapower
      GroupName: Datapower   
      VpcId: vpc-db3c9db2
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          FromPort: 9090
          ToPort: 9090
          CidrIp: 195.78.206.64/26
        -
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 195.78.206.64/26
        -
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 195.78.206.64/26  
        -
          IpProtocol: "icmp"         
          FromPort: -1
          ToPort: -1
          Description: "Allow ICMP traffic"
          CidrIp: "195.78.206.64/26"
        - 
          IpProtocol: tcp
          FromPort: 161
          ToPort: 162
          Description: "Allow SNMP traffic"
          CidrIp: 195.78.206.64/26
        -  
          IpProtocol: tcp
          FromPort: 10443
          ToPort: 10443
          Description: "Allow 10443 traffic"
          CidrIp: 195.78.206.64/26