AWSTemplateFormatVersion: '2010-09-09'
Description: EventBridge CloudFormation Nested Template

Parameters:

  Project:   
    Description: project name
    Type: String
    Default: swp-vgi-il-2
  Wltpfrif752JobName:
    Description: Wltpfrif752 job name
    Type: String
    Default: Wltpfrif752

  Env:
    Type: String

Mappings:
  EventBridgeSQSMap:
    'eb-sqs-batch-stack':
      url: https://shared-swp-vgi-il-2-nestedstacks-s3.s3.eu-central-1.amazonaws.com/eventbridge-sqs-jobs.yml

Resources:

  Wltpfrif752EventBridge:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        Project: !Ref Project 
        JobName: "Wltpfrif752"
        ScheduleExpression: " cron(0/30 22-5 * * ? *)" 
        Env: !Ref Env
      TemplateURL: !FindInMap [EventBridgeSQSMap, 'eb-sqs-batch-stack', url]

  IvaEventBridge:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        Project: !Ref Project 
        JobName: "swpIva"
        ScheduleExpression: " rate(15 minutes)"         
        Env: !Ref Env
      TemplateURL: !FindInMap [EventBridgeSQSMap, 'eb-sqs-batch-stack', url]


  TrattamentiFiscaliEventBridge:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        Project: !Ref Project 
        JobName: "swpTrattamentiFiscali"
        ScheduleExpression: " rate(15 minutes)"         
        Env: !Ref Env
      TemplateURL: !FindInMap [EventBridgeSQSMap, 'eb-sqs-batch-stack', url]  

  HostImportEventBridge:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        Project: !Ref Project 
        JobName: "host-import"
        ScheduleExpression: " rate(15 minutes)"         
        Env: !Ref Env
      TemplateURL: !FindInMap [EventBridgeSQSMap, 'eb-sqs-batch-stack', url]

  Gm66ImportEventBridge:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        Project: !Ref Project 
        JobName: "gm66-import"
        ScheduleExpression: " rate(15 minutes)"         
        Env: !Ref Env
      TemplateURL: !FindInMap [EventBridgeSQSMap, 'eb-sqs-batch-stack', url]

  DmsImportEventBridge:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        Project: !Ref Project 
        JobName: "dms-import"
        ScheduleExpression: " rate(15 minutes)"         
        Env: !Ref Env
      TemplateURL: !FindInMap [EventBridgeSQSMap, 'eb-sqs-batch-stack', url]

  ScheduledTasksEventBridge:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        Project: !Ref Project 
        JobName: "scheduled-tasks"
        ScheduleExpression: " cron(0 7 * * ? *)"  
        ActionType: "folder-check-deadline"       
        Env: !Ref Env
      TemplateURL: !FindInMap [EventBridgeSQSMap, 'eb-sqs-batch-stack', url]

  SchedulerAgendaEventBridge:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        Project: !Ref Project 
        JobName: "scheduler-agenda"
        ScheduleExpression: " cron(0 19 * * ? *)"  
        ActionType: "agenda-change-status"       
        Env: !Ref Env
      TemplateURL: !FindInMap [EventBridgeSQSMap, 'eb-sqs-batch-stack', url]
      